### ISSUE TITLE
Animal description is cut off

### ISSUE THREAD

**Issue by cbrandao18** [petfinder-com/petfinder-js-sdk#12]
Hello!

I'm finding that the animal description is always limited to 100 characters (including the ellipsis) for both 'get animals' and 'get animal' endpoints. Is there a way to access the full animal description through the API?

Thanks!

**Comment by ivorisoutdoors** [comment]
This isn't documented very well, but this is expected behavior of the API. We encourage users of the API to send people back to the Petfinder.com detail page (provided in the animal response) where the full animal description is available.
If you feel you need full access to the animal description, please open a support request with our team. https://www.petfinder.com/developers/support/

Thanks!

**Comment by crew102** [comment]
Hi @mloberg , I was hoping to get access to the full animal description field directly from the API if possible (i.e., without having to send a separate request using the `url` field that gets returned by the API). I was having trouble opening up a request for this using that that link you provided above, though, as I wasn't able to log in to salesforce. Do you know if there is some other avenue by which I can request full access to the description field?

Thanks,
Chris
